import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// @ts-ignore: side-effect import of CSS without type declarations
import "./globals.css";
import type { ReactNode } from "react"
import Navbar from "../../components/navbar/Navbar"
import AppToaster from "../../components/Toaster"
import { AnimatePresence } from "framer-motion"

const geistSans = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
})

const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
})

export const metadata: Metadata = {
  title: "Connectra",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`
          ${geistSans.variable}
          ${geistMono.variable}
          antialiased
          bg-white
          text-gray-900
          overflow-x-hidden
        `}
      >
        <Navbar />

        <AnimatePresence mode="wait">
          {children}
        </AnimatePresence>

        <AppToaster />
      </body>
    </html>
  )
}